platform :osx, "10.9"

pod 'BushidoCore/Core', path: '..'
pod 'BushidoCore/Foundation', path: '..'
pod 'BushidoCore/AppKit', path: '..'
pod 'BushidoCore/CoreGraphics', path: '..'
pod 'BushidoCore/JavaScriptCore', path: '..'
